DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

DROP TABLE IF EXISTS classroom;
CREATE TABLE classroom (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  classname TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
